# Generated by Django 4.1.1 on 2022-10-11 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_auto_20221010_0002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
